name: onlineshopnina
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
    


  cupertino_icons: ^1.0.2
  http: ^0.13.5
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
     - ./lib/assets/logo2.png
     - ./lib/assets/logo.png
     - ./lib/assets/baju1png.png
     - ./lib/assets/baju2png.png
     - ./lib/assets/baju3png.png
     - ./lib/assets/baju4png.png
     - ./lib/assets/baju5png.png
     - ./lib/assets/celana1png.png
     - ./lib/assets/celana2png.png
     - ./lib/assets/rok1png.png
     - ./lib/assets/rok2png.png
     - ./lib/assets/topi1png.png
     - ./lib/assets/banner.jpg
     - ./lib/assets/cardbaju.png
     - ./lib/assets/bajucard.png
     - ./lib/assets/celanabaru2.png
     - ./lib/assets/topibaru2.png
     - ./lib/assets/kemejabaru.png
     - ./lib/assets/rokbaru.png
     - ./lib/assets/jaketbaru.png
     - ./lib/assets/keranjangbaru.png
     - ./lib/assets/detailbaru.png




